package com.taskforge.user.entity;

import com.taskforge.tenant.entity.Tenant;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * TenantUser — the join table entity representing a User's membership in a Tenant.
 *
 * <p><b>Why a dedicated entity for a join table?</b>
 * The {@code tenant_users} table carries extra data beyond the two foreign keys:
 * a {@code role} (ADMIN/MANAGER/MEMBER/VIEWER) and a {@code joined_at} timestamp.
 * A pure {@code @ManyToMany} can't hold extra columns, so we model this as a proper
 * entity with explicit {@code @ManyToOne} relationships on both sides.
 *
 * <p><b>Tenant-scoped table:</b>
 * {@code tenant_users} HAS a {@code tenant_id} column (RLS enabled in V7).
 * This entity therefore includes the {@code tenantId} field for RLS compliance.
 * We also hold a {@code @ManyToOne Tenant} reference for convenience queries.
 *
 * <p><b>No soft-delete here:</b>
 * When a user is removed from a tenant, this row is hard-deleted (the "membership"
 * simply no longer exists). The User and Tenant entities themselves are soft-deleted.
 * Note: unlike other entities, {@code tenant_users} has no {@code deleted_at} column
 * in the schema, so we don't extend BaseEntity — we manage {@code id} and
 * {@code joined_at} directly.
 *
 * <p><b>Why not extend BaseEntity?</b>
 * BaseEntity adds {@code created_at}, {@code updated_at}, and {@code deleted_at}.
 * The schema for {@code tenant_users} only has {@code joined_at} (no updated/deleted).
 * Extending BaseEntity would require mapping non-existent columns, causing Hibernate
 * validation errors. We keep it simple and self-contained.
 */
@Entity
@Table(
    name = "tenant_users",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uq_tenant_users_tenant_user",
            columnNames = {"tenant_id", "user_id"}
        )
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TenantUser {

    /**
     * Surrogate primary key — UUID generated by DB.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * The tenant (organisation) this membership belongs to.
     * Loaded lazily — we usually only need the tenant ID, not the full object.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "tenant_id", nullable = false)
    private Tenant tenant;

    /**
     * The user who is a member of the tenant.
     * Loaded lazily — avoids pulling the full User on every membership query.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The user's role within this tenant.
     * Stored as a STRING in Postgres ({@code tenant_user_role} ENUM).
     * Using {@code EnumType.STRING} makes the DB value human-readable and safe to
     * reorder — never use {@code EnumType.ORDINAL} for stored enums.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20,
            columnDefinition = "tenant_user_role")
    private TenantUserRole role;

    /**
     * Timestamp of when the user joined this tenant workspace.
     * Set once at creation; never updated.
     */
    @Column(name = "joined_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant joinedAt = Instant.now();
}
