package com.taskforge.tenant.repository;

import com.taskforge.tenant.entity.Tenant;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * TenantRepository — data access for the {@link Tenant} entity.
 *
 * <p><b>Inherited from JpaRepository:</b>
 * {@code save(T)}, {@code findById(ID)}, {@code findAll()}, {@code deleteById(ID)},
 * {@code count()}, {@code existsById(ID)} — and their paged/sorted variants.
 *
 * <p><b>Soft-delete is transparent:</b>
 * Because {@link Tenant} is annotated with {@code @Where(clause = "deleted_at IS NULL")},
 * every query generated by Spring Data (including {@code findAll()} and {@code findById()})
 * automatically appends that predicate. A tenant with a non-null {@code deleted_at} is
 * invisible to all JPA queries without any extra filtering in service code.
 *
 * <p><b>No tenant-scoping needed here:</b>
 * {@code tenants} is the root table — it is NOT scoped to another tenant and has no RLS
 * policy. {@code findAll()} legitimately returns all non-deleted tenants.
 */
@Repository
public interface TenantRepository extends JpaRepository<Tenant, UUID> {

    /**
     * Look up a tenant by its URL slug (e.g., "acme-corp").
     * Used during login to resolve which tenant a user is logging into when they
     * provide a workspace URL.
     *
     * <p>Soft-delete filter applied automatically — returns empty if the tenant is deleted.
     */
    Optional<Tenant> findBySlug(String slug);

    /**
     * Check whether a slug is already taken before creating a new tenant.
     * Faster than {@code findBySlug(...).isPresent()} — generates a COUNT query.
     */
    boolean existsBySlug(String slug);
}
