package com.taskforge.common;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

//Base entity = Provide common fields and behavior to every database entity so you don't repeat code.

/**
 * BaseEntity — Shared superclass for all persistent entities.
 *
 * <p><b>Why @MappedSuperclass?</b>
 * Basically it put the Entity column in tenant table without creating another table
 * JPA's {@code @MappedSuperclass} tells Hibernate that this class's columns should be
 * included in every subclass table — but BaseEntity itself has NO table of its own.
 * This is the DRY alternative to copy-pasting {@code id}, {@code createdAt},
 * {@code updatedAt}, and {@code deletedAt} into every entity.
 *
 * <p><b>Why @EntityListeners(AuditingEntityListener.class)?</b>
 * Spring Data JPA's {@link AuditingEntityListener} powers the {@code @CreatedDate} and
 * {@code @LastModifiedDate} annotations. On {@code save()}, it automatically populates
 * those fields — so we never set them manually.
 * Requires {@code @EnableJpaAuditing} on a {@code @Configuration} class (see JpaConfig).
 *
 * <p><b>Soft-delete pattern:</b>
 * Instead of SQL {@code DELETE}, we set {@code deletedAt = Instant.now()}.
 * Every entity's repository uses {@code @Where(clause = "deleted_at IS NULL")} so
 * "deleted" rows are invisible to normal queries — but the data is still recoverable
 * and audit logs remain intact.
 *
 * <p><b>Why @Getter/@Setter and not @Data?</b>
 * Lombok's {@code @Data} generates {@code equals()} and {@code hashCode()} based on all
 * fields — dangerous for JPA entities where proxy objects can cause infinite loops or
 * incorrect equality checks. Using {@code @Getter/@Setter} only is the safe JPA pattern.
 * Subclasses add {@code @Builder}, {@code @NoArgsConstructor}, {@code @AllArgsConstructor}
 * where needed.
 */
@Getter
@Setter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /**
     * Primary key — UUID generated by the database using {@code GenerationType.UUID}
     * (Hibernate 6+ delegates to the DB's {@code gen_random_uuid()} or uses a Java
     * UUID generator depending on dialect). UUIDs avoid auto-increment ID enumeration
     * attacks and are safe to expose in URLs.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Set once on insert by {@link AuditingEntityListener}.
     * {@code updatable = false} prevents accidental overwrites on UPDATE.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Updated automatically on every save by {@link AuditingEntityListener}.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Soft-delete timestamp. {@code null} = active record; non-null = logically deleted.
     * Use {@code SoftDeleteService.softDelete(entity)} to set this field rather than
     * calling DELETE on the repository.
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;
}
